# Generated by Django 6.0.4 on 2026-04-16 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='dish',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(default='626 Great Horton Rd, Bradford BD7 3ER', max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='01274 780810', max_length=50),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle',
            field=models.CharField(default='Grill • Shawarma • Mandi', max_length=300),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(default='BAYTUK', max_length=200),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.menucategory'),
        ),
    ]
